"""Project-owned contracts shared by every on-policy learning agent."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

import numpy as np
from numpy.typing import NDArray

if TYPE_CHECKING:
    from utils.buffers import OnPolicyRollout


class CollectionMode(StrEnum):
    """
    Specify whether an agent learns from whole episodes or fixed rollouts.
    """

    COMPLETE_EPISODES = "complete_episodes"
    FIXED_ROLLOUT = "fixed_rollout"


@dataclass(frozen=True, slots=True)
class CollectedAction:
    """
    Store the detached action quantities required by all project algorithms.

    Fields:
        * latent_action: Pre-squash action sampled by the collection policy.
        * action: Bounded action sent to the environment.
        * behaviour_log_probability: Collection-policy action log probability.
        * current_value: Critic estimate at the acted-on observation, if present.
    """

    latent_action: NDArray[np.float32]
    action: NDArray[np.float32]
    behaviour_log_probability: float | None
    current_value: float | None

    def __post_init__(self) -> None:
        """
        Preserve private float32 action copies with one shared vector shape.
        """
        latent = np.asarray(self.latent_action, dtype=np.float32)
        action = np.asarray(self.action, dtype=np.float32)
        if latent.ndim != 1 or action.ndim != 1 or latent.shape != action.shape:
            raise ValueError(
                "Collected latent and bounded actions must be matching vectors."
            )
        latent = latent.copy()
        action = action.copy()
        latent.setflags(write=False)
        action.setflags(write=False)
        object.__setattr__(self, "latent_action", latent)
        object.__setattr__(self, "action", action)
        if self.behaviour_log_probability is not None:
            object.__setattr__(
                self, "behaviour_log_probability", float(self.behaviour_log_probability)
            )
        if self.current_value is not None:
            object.__setattr__(self, "current_value", float(self.current_value))


@dataclass(frozen=True, slots=True)
class AgentUpdateInput:
    """
    Describe one complete-episode or fixed-rollout optimization input.

    Fields:
        * mode: Collection boundary that made the data eligible for learning.
        * episodes: Complete trajectories for a Monte Carlo update.
        * rollout: A fixed-length rollout for an actor-critic update.
    """

    mode: CollectionMode
    episodes: tuple[OnPolicyRollout, ...] = ()
    rollout: OnPolicyRollout | None = None

    def __post_init__(self) -> None:
        """
        Require exactly the data shape implied by the collection mode.
        """
        if self.mode is CollectionMode.COMPLETE_EPISODES:
            if not self.episodes or self.rollout is not None:
                raise ValueError(
                    "Complete-episode updates require episodes and no rollout."
                )
        elif self.episodes or self.rollout is None:
            raise ValueError(
                "Fixed-rollout updates require one rollout and no episodes."
            )


@dataclass(frozen=True, slots=True)
class AgentUpdateOutput:
    """
    Return scalar diagnostics generated by one completed optimizer update.

    Fields:
        * diagnostics: JSON-compatible scalar diagnostics owned by the algorithm.
    """

    diagnostics: dict[str, float | int | None] = field(default_factory=dict)


@runtime_checkable
class OnPolicyAgent(Protocol):
    """
    Define the learning boundary for bounded continuous on-policy agents.

    Agents own models, optimizers, policy/minibatch random generators and their
    serializable state. The shared engine owns environment interaction,
    normalization, episode lifecycle and accounting.
    """

    collection_mode: CollectionMode
    collection_size: int

    def collect_action(
        self, normalized_observation: NDArray[np.float32]
    ) -> CollectedAction:
        """
        Sample one stochastic bounded action for training collection.
        """
        ...

    def deterministic_action(
        self, normalized_observation: NDArray[np.float32]
    ) -> NDArray[np.float32]:
        """
        Return one bounded action without consuming a training random stream.
        """
        ...

    def bootstrap_value(
        self, normalized_observation: NDArray[np.float32]
    ) -> float | None:
        """
        Return a detached critic value for one bootstrap state when applicable.
        """
        ...

    def update(self, update_input: AgentUpdateInput) -> AgentUpdateOutput:
        """
        Optimize owned state from detached rollout records.
        """
        ...

    def state_dict(self) -> dict[str, Any]:
        """
        Return all owned model, optimizer and mutable generator state.
        """
        ...

    def load_state_dict(self, state: dict[str, Any]) -> None:
        """
        Restore all owned model, optimizer and mutable generator state.
        """
        ...
